### ISSUE TITLE
Schedule change

### ISSUE THREAD

**Issue by sonejostudios** [linux-audio-berlin/LAC16#58]
Hey,

because we both focused on live music we decided put Fabla2 and Linux Live on Stage together in the Mainhall.

New Schedule: 
-Fabla2 : 12h-12h45
-LinuxLiveonStage: 12h45-13h30

**Comment by dvzrv** [comment]
Oh, I misunderstood Harry yesterday then.
Will change

**Comment by dvzrv** [comment]
Hmm, as I said yesterday, you're killing my lunch break with this! ;-)
Will have you start around 13:00h though. Without a break in between this will turn into a mess.

**Comment by sonejostudios** [comment]
well, we need at least 45mn i guess... if possible we would start at 12:50 after a short breat (all depending on harry's end time).

**Comment by harryhaaren** [comment]
I see schedule is updated, with both OpenAV and Linux-Live in that slot - awesome.

@sonejostudios - I'll keep it to 45 mins in duration (there will be enough time during the weekend to do more workshops / hands on with people directly if they want)

**Comment by IARI** [comment]
@harryhaaren @dvzrv
15 minutes break would mean we only have 30 minutes, unless we dont care for the food-break thing.
Since I'm totally new to the scene an haven't been to a lac before, I have no idea, how this is handled.
I would really prefer if we could have 45 minutes total - can we somehow manage that?

**Comment by IARI** [comment]
@harryhaaren @dvzrv
15 minutes break would mean we only have 30 minutes, unless we dont care for the food-break thing.
Since I'm totally new to the scene an haven't been to a lac before, I have no idea, how this is handled.
I would really prefer if we could have 45 minutes total - can we somehow manage that?

**Comment by Vampouille** [comment]
+1 It would be nice to see you 45 minutes !

**Comment by IARI** [comment]
@Vampouille are you coming??!? ;D <3

**Comment by Vampouille** [comment]
No I'm not coming, I did not found cheap ticket for Berlin :-( but I want to see your presentation !

**Comment by dvzrv** [comment]
@IARI: no.
12:00 - 12:45
13:00 - 14:30
